//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDNApplication.Data.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class labels_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal labels_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CDNApplication.Data.Resources.labels_en", typeof(labels_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CDNApplicationProgressApplicantDetails {
            get {
                return ResourceManager.GetString("CDNApplicationProgressApplicantDetails", resourceCulture);
            }
        }
        
        internal static string CDNApplicationProgressMailingAddress {
            get {
                return ResourceManager.GetString("CDNApplicationProgressMailingAddress", resourceCulture);
            }
        }
        
        internal static string CDNApplicationProgressIdentityDocuments {
            get {
                return ResourceManager.GetString("CDNApplicationProgressIdentityDocuments", resourceCulture);
            }
        }
        
        internal static string CDNApplicationProgressSignature {
            get {
                return ResourceManager.GetString("CDNApplicationProgressSignature", resourceCulture);
            }
        }
    }
}
